name: ZITADEL CI/CD Pipeline

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  core:
    uses: ./.github/workflows/core.yml
    with:
      node_version: "20"
      buf_version: "latest"

  console:
    uses: ./.github/workflows/console.yml
    with:
      node_version: "20"
      buf_version: "latest"

  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: "23.0.8"
      dry_run: true

  compile:
    needs: [core, console, version]
    uses: ./.github/workflows/compile.yml
    with:
      core_cache_key: ${{ needs.core.outputs.cache_key }}
      console_cache_key: ${{ needs.console.outputs.cache_key }}
      core_cache_path: ${{ needs.core.outputs.cache_path }}
      console_cache_path: ${{ needs.console.outputs.cache_path }}
      version: ${{ needs.version.outputs.version }}

  lint:
    needs: [core, console]
    uses: ./.github/workflows/lint.yml
    with:
      node_version: "18"
      buf_version: "latest"
      go_lint_version: "v1.64.8"
      core_cache_key: ${{ needs.core.outputs.cache_key }}
      core_cache_path: ${{ needs.core.outputs.cache_path }}

  container:
    needs: [compile]
    uses: ./.github/workflows/container.yml
    secrets: inherit
    permissions:
      packages: write
    with:
      build_image_name: "southguild/zitadel-build"

  release:
    uses: ./.github/workflows/release.yml
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    needs: [version, lint]
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      build_image_name: ${{ needs.container.outputs.build_image }}
      semantic_version: "23.0.8"
      image_name: "southguild/zitadel"
