name: Release

on:
  workflow_call:
    inputs:
      semantic_version:
        required: true
        type: string
      build_image_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKER_HUB_TOKEN:
        description: "Docker Hub token"
        required: true

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: ${{ inputs.semantic_version }}
      dry_run: false

  docker:
    runs-on: ubuntu-22.04
    needs: [version]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish ${{ needs.version.outputs.version }}
        run: |
          docker buildx imagetools create \
            --tag ${{ inputs.image_name }}:${{ needs.version.outputs.version }} \
            ${{ inputs.build_image_name }}
          docker buildx imagetools create \
            --tag ${{ inputs.image_name }}:${{ needs.version.outputs.version }}-debug \
            ${{ inputs.build_image_name }}-debug
      - name: Publish latest
        if: ${{ github.ref_name == 'next' }}
        run: |
          docker buildx imagetools create \
            --tag ${{ inputs.image_name }}:latest \
            ${{ inputs.build_image_name }}
          docker buildx imagetools create \
            --tag ${{ inputs.image_name }}:latest-debug \
            ${{ inputs.build_image_name }}-debug
